section_content.section_entity.*:
  type: config_entity
  label: Section Entity
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    urlPattern:
      type: string
      label: "URL Pattern"
    color:
      type: string
      label: Color
