<?php

function example_views_views_data() {
  $data = [];
  $data['forcontu_node_highlighted'] = [];
  $data['forcontu_node_highlighted']['table'] = [];
  // represents the name of the category when you add a new field to the view
  $data['forcontu_node_highlighted']['table']['group'] = t('Example views');
  // name of the machine that implements this hook and that is also responsible for the external table
  $data['forcontu_node_highlighted']['table']['provider'] = 'example_views';
  $data['forcontu_node_highlighted']['table']['join']  = [

    'node_field_data' => [
      'left_field' => 'nid',
      'field' => 'nid',
    ],
  ];

  $data['forcontu_node_highlighted']['highlighted'] = [
    'title' => t('Highlighted content'),
    'help' => t('Boolean field for highlighted content.'),
    'field' => [
      'id' => 'boolean_icon',
    ],
    'sort' => [
    'id' => 'highlighted_order',
    ],
    'filter' => [
      'id' => 'boolean',
      'label' => t('Highlighted'),
      'type' => 'yes-no',
      'use_equal' => TRUE,
    ]
  ];

  $data['forcontu_node_highlighted']['highlighted_recent'] = [
    'title' => t('Highlighted recent content'),
    'help' => t('Highlighted recent content.'),
    'filter' => [
      'id' => 'highlighted_recent',
      'label' => t('Highlighted recent'),
    ],
  ];

  return $data;
}

/**
 * Implements hook_views_data_alter().
 */
function example_views_views_data_alter(array &$data) {
  if (isset($data['node_field_data'])) {
    $data['node_field_data']['published_by_on'] = [
      'title' => t('Published by'),
      'field' => [
        'id' => 'published_by_on',
      ],
    ];
  }
}