<?php

/**
 * @file
 * Primary module hooks for Forcontu block module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_block_view_alter().
 */
//function forcontu_block_block_view_alter(array &$build, BlockPluginInterface $block) {
//  if ($block->getPluginId() == 'system_powered_by_block') {
//    // hacemos visible el label del bloque
//    $build['#configuration']['label_display'] = BlockPluginInterface::BLOCK_LABEL_VISIBLE;
//  }
//}


/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function forcontu_block_block_view_system_powered_by_block_alter(array &$build, BlockPluginInterface $block) {
  if ($block->getPluginId() == 'system_powered_by_block') {
    $build['#configuration']['label_display'] = BlockPluginInterface::BLOCK_LABEL_VISIBLE;
  }
}

/**
 * Implements hook_block_access().
 */
function forcontu_block_block_access(\Drupal\block\Entity\Block $block, $operation, \Drupal\Core\Session\AccountInterface $account) {
  // Example code that would prevent displaying the 'Powered by Drupal' block in
  // a region different from the footer.
  if ($operation == 'view' && $block->getPluginId() == 'system_powered_by_block') {
    return AccessResult::forbiddenIf($block->getRegion() != 'footer')->addCacheableDependency($block);
  }

  // No opinion.
  return AccessResult::neutral();
}
