<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter.
 *
 */

//function forcontu_forms_form_alter(&$form, FormStateInterface $form_state, $form_id)
//{
//    // dpm($form_id);
//
//    switch ($form_id) {
//        case 'system_site_information_settings':
//            dpm($form);
//            $form['site_information']['site_slogan']['#required'] = TRUE;
//            break;
//
//        case 'node_page_form':
//        case 'node_page_edit_form':
//
//           dpm($form);
//            // Open options group
//            $form['options']['#open'] = TRUE;
//            // Add element highlighted
//            $form['options']['highlighted'] = [
//                '#type' => 'checkbox',
//                '#title' => t('Highlighted'),
//                '#weight' => 100,
//            ];
//
//           break;
//    }
//}


/**
 * Implements hook_form_FORM_ID_alter() for system_site_information_settings.
 */

function forcontu_forms_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state)
{
    $form['site_information']['site_slogan']['#required'] = TRUE;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 */
function forcontu_forms_form_node_form_alter(
    &$form,
    FormStateInterface $form_state,
    $form_id
) {
    // show base form id
    // dpm($form_state->getBuildInfo()['base_form_id']);
    $highlighted = 0;

    if ($nid = $form_state->getFormObject()->getEntity()->id()) {

        $connection = \Drupal::database();
        $highlighted = $connection->select('forcontu_node_highlighted', 'f')
            ->fields('f', ['highlighted'])
            ->condition('f.nid', $nid)
            ->execute()
            ->fetchField();
    }

    $form['options']['#open'] = TRUE;

    $form['options']['highlighted'] = [
        '#type' => 'checkbox',
        '#title' => t('Highlighted'),
        '#weight' => 100,
        '#default_value' => $highlighted
    ];

    $form['actions']['submit']['#submit'][] =
        'forcontu_forms_form_node_form_submit';
}

function forcontu_forms_form_node_form_submit(
    array &$form,
    FormStateInterface $form_state
) {
    $nid = $form_state->get('nid');
    $highlighted = $form_state->getValue('highlighted');

    // dpm($nid, $highlighted);

    $connection = \Drupal::database();

    $upsert = $connection->upsert('forcontu_node_highlighted')
        ->key('nid')
        ->fields(['nid', 'highlighted'])
        ->values([
            'nid' => $nid,
            'highlighted' => $highlighted,
        ])->execute();
}
