<?php

/**
 * @file
 * Primary module hooks for Ja Theming module.
 */

/**
 * Implements hook_theme().
 */
function ja_theming_theme($existing, $type, $theme, $path) {
  return [
    'theming_dimensions' => [
      'variables' => [
        'length' => NULL,
        'width' => NULL,
        'height' => NULL,
        'unit' => 'cm',
      ],
      'template' => 'theming-dimensions'
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */

// Otra forma de implementar los estilos css con el hook_proprocess_HOOK()
// hook es el nombre del modulo
// HOOK es el nombre de la plantilla
//function ja_theming_preprocess_theming_dimentions(&$variables) {
//  $variables['#attached']['library'] = ['ja_theming/ja_theming_styles.css'];
//}
