message.message_type.*:
  type: config_entity
  label: Message type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string