<?php

use Drupal\Component\Utility\Html;
/**
 * Implements hook_mail()
 */
function ja_email_example_mail($key, &$message, $params): void {
  $options = [
    'langcode' => $message['langcode']
  ];

  switch ($key) {
    case 'contact_message':

      $message['from'] = \Drupal::config('system.site')->get('mail');
//      $from = \Drupal::config('system.site')->get('mail');

      $site_name = \Drupal::config('system.site')->get('name');
      $message['subject'] = t('E-mail sent from @site-name',
      ['@site-name' => $site_name], $options);

      $username = \Drupal::currentUser()->getDisplayName();
      $message['body'][] = t('@name sent you the following message:', ['@name' => $username], $options);
      $message['body'][] = Html::escape($params['message']);
      break;
  }
}